# Generated by Django 4.2.14 on 2024-07-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0040_update_password_reset_links_in_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RORImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('stopped', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('is_ongoing', 'Ongoing'), ('is_unnecessary', 'Unnecessary'), ('is_successful', 'Successful'), ('is_failed', 'Failed')], default='is_ongoing', max_length=20)),
                ('records', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'ROR import',
                'verbose_name_plural': 'ROR imports',
                'get_latest_by': 'started',
            },
        ),
        migrations.CreateModel(
            name='RORImportError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('ror_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.rorimport')),
            ],
            options={
                'verbose_name': 'ROR import error',
                'verbose_name_plural': 'ROR import errors',
            },
        ),
    ]
